/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline": "#6d7a75",
        "on-secondary-container": "#57657b",
        "surface-container-low": "#eff5f1",
        "surface-variant": "#dee4e0",
        "inverse-primary": "#5fdbbd",
        "surface-container": "#e9efeb",
        "outline-variant": "#bccac4",
        "tertiary": "#9b4330",
        "primary-container": "#0fa58a",
        "tertiary-fixed-dim": "#ffb4a4",
        "secondary-fixed-dim": "#b9c7e0",
        "surface-container-high": "#e3eae6",
        "inverse-surface": "#2b322f",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#571104",
        "on-tertiary-fixed-variant": "#7c2d1b",
        "primary": "#006b59",
        "background": "#f5fbf7",
        "on-error": "#ffffff",
        "on-primary-container": "#003228",
        "on-secondary-fixed": "#0d1c2f",
        "error": "#ba1a1a",
        "surface-bright": "#f5fbf7",
        "on-surface": "#171d1b",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#d5e3fd",
        "on-secondary": "#ffffff",
        "secondary-container": "#d5e3fd",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "primary-fixed": "#7df8d9",
        "inverse-on-surface": "#ecf2ee",
        "tertiary-container": "#dc755e",
        "secondary": "#515f74",
        "on-primary-fixed-variant": "#005142",
        "on-background": "#171d1b",
        "surface-tint": "#006b59",
        "surface-container-highest": "#dee4e0",
        "on-surface-variant": "#3d4945",
        "on-error-container": "#93000a",
        "tertiary-fixed": "#ffdad3",
        "surface-dim": "#d5dbd8",
        "primary-fixed-dim": "#5fdbbd",
        "on-secondary-fixed-variant": "#3a485c",
        "surface": "#f5fbf7",
        "on-primary-fixed": "#002019",
        "on-tertiary-fixed": "#3d0600"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "container-margin-sm": "16px",
        "unit": "4px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "24px",
        "gutter": "16px",
        "container-margin-lg": "24px"
      },
      fontFamily: {
        "headline-lg": ["Inter"],
        "emergency-callout": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "body-lg": ["Inter"],
        "display": ["Inter"],
        "title-md": ["Inter"],
        "label-caps": ["Inter"],
        "body-sm": ["Inter"]
      },
      fontSize: {
        "headline-lg": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "emergency-callout": ["18px", {"lineHeight": "24px", "fontWeight": "700"}],
        "headline-lg-mobile": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "display": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "title-md": ["18px", {"lineHeight": "24px", "fontWeight": "600"}],
        "label-caps": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
